let odpowiedzi = [
    "bo jesteś moim najwspanialszym misiem",
    "bo zawsze poprawiasz mi humor",
    "bo przy tobie czuję się bezpiecznie",
    "bo mnie rozśmieszasz",
    "bo masz piękny uśmiech",
    "bo kocham twoje oczy",
    "bo jesteś słodki",
    "bo jesteś kochany",
    "bo zawsze mnie wspierasz",
    "bo mnie rozumiesz",
    "bo jesteś cierpliwy",
    "bo przy tobie mogę być sobą",
    "bo jesteś wyjątkowy",
    "bo jesteś najlepszym chłopakiem",
    "bo umiesz mnie uspokoić",
    "bo dajesz mi szczęście",
    "bo kochasz mnie taką, jaka jestem",
    "bo jesteś moim domem",
    "bo jesteś goofy",
    "bo tęsknię za tobą nawet po chwili",
    "bo jesteś moim ulubionym człowiekiem",
    "bo zawsze o mnie pamiętasz",
    "bo dbasz o mnie",
    "bo jesteś troskliwy",
    "bo jesteś moim wsparciem",
    "bo jesteś mądry",
    "bo masz dobre serce",
    "bo jesteś cudowny",
    "bo zawsze mogę na ciebie liczyć",
    "bo jesteś moim szczęściem",
    "bo uwielbiam z tobą rozmawiać",
    "bo jesteś moim spokojem",
    "bo sprawiasz, że się uśmiecham",
    "bo jesteś uroczy",
    "bo kocham twój głos",
    "bo kocham twój śmiech",
    "bo jesteś najlepszy",
    "bo masz fajnego bica",
    "bo sprawiasz, że każdy dzień jest lepszy",
    "bo przy tobie wszystko wydaje się łatwiejsze",
    "bo jesteś moim ulubionym misiem",
    "bo jesteś opiekuńczy",
    "bo jesteś szczery",
    "bo jesteś wierny",
    "bo jesteś wyrozumiały",
    "bo umiesz mnie pocieszyć",
    "bo jesteś romantyczny",
    "bo zawsze jesteś obok, kiedy cię potrzebuję",
    "bo kocham spędzać z tobą czas",
    "bo jesteś moim wszystkim",
    "bo jesteś moim szczęśliwym miejscem",
    "bo uwielbiam twoje przytulasy",
    "bo zawsze umiesz mnie rozweselić",
    "bo jesteś moim słońcem",
    "bo jesteś moim niunkiem",
    "bo jesteś moim światem",
    "bo jesteś moim ulubionym głupkiem",
    "bo jesteś przesłodki",
    "bo jesteś dzielny",
    "bo jesteś silny",
    "bo jesteś ambitny",
    "bo jesteś cudownym człowiekiem",
    "bo przy tobie czuję motylki",
    "bo jesteś moim szczęściem każdego dnia",
    "bo kocham twoje objęcia",
    "bo kocham twoje pocałunki",
    "bo kocham każdą chwilę z tobą",
    "bo sprawiasz, że wierzę w miłość",
    "bo jesteś moim najlepszym przyjacielem",
    "bo jesteś moim marzeniem, które się spełniło",
    "bo nigdy nie chcę cię stracić",
    "bo jesteś jedyny",
    "bo jesteś najważniejszy",
    "bo kocham wszystko, co z tobą związane",
    "bo jesteś moim ulubionym miejscem",
    "bo jesteś moim spokojem po ciężkim dniu",
    "bo jesteś słodziakiem",
    "bo jesteś moim skarbem",
    "bo jesteś moim koteczkiem",
    "bo mogę przy tobie puszczać baki",
    "bo jesteś moim misiem",
    "bo kocham, jak się o mnie martwisz",
    "bo jesteś delikatny",
    "bo jesteś zabawny",
    "bo jesteś najlepszą częścią mojego dnia",
    "bo jesteś moim szczęśliwym losem",
    "bo jesteś moim ulubionym powodem do uśmiechu",
    "bo kocham cię bardziej każdego dnia",
    "bo przy tobie czuję się kochana",
    "bo jesteś moim bezpiecznym miejscem",
    "bo jesteś idealny dla mnie",
    "bo jesteś moim słodkim okruszkiem",
    "bo jesteś moim całym sercem",
    "bo kocham, jak mówisz do mnie",
    "bo kocham twoją obecność",
    "bo jesteś moim największym szczęściem",
    "bo jesteś moim na zawsze i jeszcze dłużej",
    "bo zawsze wybieram ciebie",
    "bo nie wyobrażam sobie życia bez ciebie"
];

function losuj() {
    let numer = Math.floor(Math.random() * odpowiedzi.length);
    document.getElementById("wynik").innerHTML = odpowiedzi[numer];
}